### ISSUE TITLE
lastpass-ssh does not fetch ssh keys

### ISSUE THREAD

**Issue by zaro0508** [wkoszek/lastpass-ssh#2]
I tried using this with my lastpass account but couldn't get it to work.  I have LastPass CLI v1.1.2 and have it setup with 2 factor authentication.  Was wondering if there's something I'm missing to get it to work?

I did the following:
1. Manually added my ssh key to lastpass.
    name: id_rsa
    folder: SSH
    note type: SSH Key
2. ran "lpass --login me@gmail.com" on command line to login to my lastpass acccount

*Note- I can view my account info with "lpass ls" and "lpass show" commands.
from "lpass show id_rsa": 
```
Date: ,,
Hostname: my-Folio-9470m
Public Key: $MY_PUBLIC_KEY
DEK-Info:  AES-128-CBC,AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
Proc-Type:  4,ENCRYPTED
Private Key: $MY_PRIVATE_KEY
Passphrase: 
Format: AES
Bit Strength: 128
NoteType: SSH Key
Notes: My Key
```

3. ran "lastpass-ssh --keys-path ~/.sshtest" to fetch ssh key

No keys are aded to  ~/.sshtest folder

**Comment by zaro0508** [comment]
Actually I noticed that my `SSH` folder wasn't under the `Secure Notes` folder.  Once I changed that lastpass-ssh did seem to attempt to fetch the ssh key.

**Comment by wkoszek** [comment]
@zaro0508 Let me know if it worked afterwards.
