### ISSUE TITLE
Script tries adding non-existent key

### ISSUE THREAD

**Issue by spacemud** [wkoszek/lastpass-ssh#3]
Thanks for this script - works great.

I notice that when running `lastpass-ssh` that it tries adding a key that doesn't exist before successfully loading the keys found in `Secure Notes/SSH`:

```
LastPass key ID  name id /Users/dan/.ssh/id: No such file or directory
LastPass key ID XXXXXXXXXXXXXXXXXXX name id_rsa Identity added: /Users/dan/.ssh/id_rsa (/Users/dan/.ssh/id_rsa)
```

I only have a single key in `Secure Notes/SSH`, and that is `id_rsa`. This is on macOS Sierra 10.12.5.

**Comment by wkoszek** [comment]
@spacemud Thanks for the report. You're right. Let me look into it. If you've managed to solve it already, feel free to submit a pull request. I'm looking for more eyes to look into this code. I offer nothing but the credit :-)

**Comment by Awesomecase** [comment]
The reason it does that is every folder has a base id in` lpass ls`. If you change line 67 from
`lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }`
to
`lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }[1..-1]`
it works. As evidenced by
 

```
(rdb:1) raw_lines
"Secure Notes\\SSH/ [id: XXXXXXXXXXXXXX]\nSecure Notes\\SSH/Github [id: XXXXXXXXXXXX]\n"

(rdb:1) lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }
["Secure Notes\\SSH/ [id: XXXXXXXXXXXXX]", "Secure Notes\\SSH/Github [id: XXXXXXXXXXXX]"]

(rdb:1) lines = raw_lines.split("\n").select { |l| l if l =~ /^Secure/ }[1..-1]
["Secure Notes\\SSH/Github [id: XXXXXXXXXXXXX]"]
```
I've tested it on 2 keys
```
4096 SHA256:GT68UMN3ol33tYAzsz4iooiS7RQzNfS9NYYs/BfTLZE /home/cole/.ssh/test (RSA)
4096 SHA256:E385D3uHuXREonnujF8kkXUPmfL2w2bHVoTpYRNzihg /home/cole/.ssh/test2 (RSA)
```
and I don't get the 
`LastPass key ID  name id /Users/dan/.ssh/id: No such file or directory` message.
