### ISSUE TITLE
Use Printf to automatically escape password string

### ISSUE THREAD

**Issue by ghost** [wkoszek/lastpass-ssh#7]
Use printf to escape the password string, this would resolve the possible scenario where a password contains unescape double quotes. I've modified my code to the following:

printf -v PWD "%q" "$(lpass show --field=Passphrase ssh/$(basename ${KEY_NAME}))"

This way the PWD variable automatically escapes special characters.

**Comment by wkoszek** [comment]
@JWillis1370 Which file are you talking about?
